(function(g){var window=this;var G2=function(a){var b={languageCode:a.i,languageName:a.l,displayName:g.pz(a),kind:a.o,name:a.u,id:a.H,is_servable:a.C,is_default:a.isDefault,is_translateable:a.D,vss_id:a.A};a.g&&(b.translationLanguage=a.g);return b},H2=function(a){return a.g?a.g.languageCode:a.i},Qpa=function(a,b){var c=new g.oz;
c.i=a.i;c.l=a.l;c.u=a.u;c.o=a.o;c.isDefault=!1;c.C=a.C;c.D=a.D;c.A=a.A;c.F=a.F;c.g=b;return c},Rpa=function(){this.i=[];
this.g=[]},I2=function(a,b){return b?a.g.concat(a.i):a.g},J2=function(a,b){switch(b.o){case "asr":var c=a.i;
g.Za(c,(0,g.x)(b.dr,b))||c.push(b);break;default:c=a.g,g.Za(c,(0,g.x)(b.dr,b))||c.push(b)}},K2=function(a){g.F.call(this);
this.Va=a;this.i=new Rpa;this.u=[]},L2=function(a,b,c){K2.call(this,a);
this.g=null;this.u=b.Bu;this.l=c},M2=function(){this.Ua=[]},N2=function(a,b,c,d,e,f){g.F.call(this);
this.H=a;this.l=b;this.R=g.W(b);this.u=new M2;this.g=null;this.C=d;this.I=f;this.i=this.o=null;this.M=c;this.A=e||!1;this.D=new g.J(this.bx,1E3,this);g.I(this,this.D);this.F=new g.hs(this);g.I(this,this.F);this.F.K(b,"SEEK_COMPLETE",this.Ix);this.Ix();this.bx()},O2=function(a,b){b-=a.l.Ab();
var c=a.g;a.g=g.Xa(a.M.xf(b).g);c!=a.g&&a.I&&a.I()},P2=function(a,b){var c=g.nv(g.yv(b,a.H,{})),d={format:"RAW",
withCredentials:!0};a.A&&(d.responseType="arraybuffer");a.i=g.wq(c,d,3,100).then((0,g.x)(a.FK,a));a.o=b;c=a.u;d=a.o.g[0].i;var e=g.qb(c.Ua,d);0<=e||0>e&&1==(-e-1)%2||(e=-e-1,0<e&&1==d-c.Ua[e-1]&&e<c.Ua.length&&1==c.Ua[e]-d?(g.eb(c.Ua,e),g.eb(c.Ua,e-1)):0<e&&1==d-c.Ua[e-1]?c.Ua[e-1]=d:e<c.Ua.length&&1==c.Ua[e]-d?c.Ua[e]=d:(g.nb(c.Ua,e,0,d),g.nb(c.Ua,e+1,0,d)))},Q2=function(a,b){K2.call(this,g.W(b));
this.g=a;this.C=b;this.l=null;this.o=!1;this.A=g.Ry(g.W(this.C))&&!this.g.i},R2=function(a,b){var c=[],d;
for(d in a.g.g){var e=a.g.g[d];if(g.gV(e,b||null)){var f="en",k="English",l=".en",m="";if(e=e.info.captionTrack)f=e.languageCode,k=e.displayName,l=e.vssId,m=e.kind;c.push(new g.oz({id:d,languageCode:f,languageName:k,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},Spa=function(a,b){return null!=b&&b in a.g.g?a.g.g[b]:null},S2=function(a,b,c){var d=[],e;
for(e in a.g.g){var f=a.g.g[e];if(g.gV(f,c||null)){var k=f.info.captionTrack;k&&k.languageCode==b&&d.push(f)}}return d.length?d[0]:null},T2=function(a,b,c,d,e){K2.call(this,e||null);
c=c||g.Dp(a).hl||"";c=c.split("_").join("-");this.o=g.Fp(a,{hl:c});this.l=b;this.A=!!d;this.C={};this.g=null},U2=function(a){if(!Tpa.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(Upa,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.substr(1),16);return[a>>16,a>>8&255,a&255]},V2=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.KD.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.l=f;this.g=k},W2=function(a,b,c,d,e){g.KD.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.g=[]},Y2=function(a){a=void 0===a?{}:a;
var b="_"+X2++;return new W2(0,0x8000000000000,0,b,a)},$2=function(a,b,c,d,e,f){var k={};
g.Sa(k,b);g.Sa(k,a.params);g.Sa(k,c);var l={};g.Sa(l,b.vb);a.params.vb&&g.Sa(l,a.params.vb);g.Sa(l,c.vb);k.vb=l;g.V.call(this,{B:"div",G:"caption-window",L:{id:"caption-window-"+a.id,dir:1==k.Be?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:k.lang},J:[{B:"span",G:"captions-text",L:{style:"word-wrap: normal; display: block;"}}]});this.C=[];this.P=!1;this.o=a;this.Y=this.S=null;this.Pa=e;this.Na=f;this.D=null;this.X=.96*e;this.wa=.96*f;this.l=k;this.Ha=c;this.A=this.i["captions-text"];this.Ca=
null!=this.A.style["box-decoration-break"]||null!=this.A.style["-webkit-box-decoration-break"];this.W=d/360*16;this.type=0;this.la=this.W*Z2(l);a=new g.ls(this.element,!0);g.I(this,a);a.subscribe("dragstart",this.WF,this);a.subscribe("dragmove",this.VF,this);a.subscribe("dragend",this.UF,this);this.va=this.na=0;b="";this.l.windowOpacity&&(a=U2(this.l.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.l.windowOpacity+")");a={"background-color":b,display:!1===this.l.isVisible?"none":"","text-align":Vpa[this.l.textAlign]};
this.Ca&&(a["border-radius"]=b?this.la/8+"px":"");if(this.u=2==this.o.params.Be||3==this.o.params.Be)b=this.element,c="vertical-rl",1==this.l.BA&&(c="vertical-lr"),g.Ld&&(c="vertical-lr"==c?"tb-lr":"tb-rl"),g.ag(b,"-o-writing-mode",c),g.ag(b,"-webkit-writing-mode",c),g.ag(b,"writing-mode",c),g.ag(b,"text-orientation","upright"),g.K(b,"ytp-vertical-caption"),3==this.o.params.Be&&(g.ag(b,"text-orientation",""),g.ag(b,"transform","rotate(180deg)"));g.ag(this.element,a);switch(this.l.Uf){case 0:case 1:case 2:g.K(this.element,
"ytp-caption-window-top");break;case 6:case 7:case 8:g.K(this.element,"ytp-caption-window-bottom")}},Z2=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0==a.offset||2==a.offset)b*=.8;return b},a3=function(a,b){var c={},d=b.background?b.background:a.l.vb.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.l.vb.backgroundOpacity;d=U2(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Ca&&(c["box-decoration-break"]="clone",c["border-radius"]=a.la/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.W*Z2(b)+"px";d=1;e=b.color||a.l.vb.color;if(b.color||null!=b.textOpacity)e=U2(e),d=null==b.textOpacity?a.l.vb.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=
e,c.fill=e;var f=b.charEdgeStyle;0==f&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";b.Ju&&(k=e=b.Ju);var l=a.W/16/2,m=Math.max(l,1),n=Math.max(2*l,1),q=Math.max(3*l,1),t=Math.max(5*l,1);d=[];switch(f){case 4:for(;q<=t;q+=l)d.push(n+"px "+n+"px "+q+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=q;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(q=0;5>q;q++)d.push("0 0 "+n+"px "+
e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.eq()?'"Carrois Gothic SC", sans-serif-smallcaps':
'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.l.vb.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Qe&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]="underline");
b.UD&&(c.visibility="hidden");1==b.WD&&a.u&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.Ty||g.Uy,3==a.o.params.Be?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1==b.Ae||2==b.Ae||3==b.Ae||4==b.Ae||5==b.Ae)if(g.Ty)c["font-weight"]="bold";else switch(c["text-emphasis"]="filled circle",c["webkit-text-emphasis"]="filled circle",b.Ae){case 4:case 3:c["text-emphasis-position"]="under left";c["webkit-text-emphasis-position"]="under left";break;
case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},b3=function(a){a.D=g.Rd("SPAN");
g.ag(a.D,{display:"block"});g.K(a.D,"caption-visual-line");a.A.appendChild(a.D)},c3=function(a,b){var c=g.Rd("SPAN");
g.ag(c,{display:"inline-block","white-space":"pre-wrap"});g.ag(c,a3(a,b));c.classList.add("ytp-caption-segment");a.D.appendChild(c);c.previousElementSibling&&(g.ag(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.ag(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},d3=function(a,b,c){a.P=a.P||!!c;
var d={};g.Sa(d,a.l.vb);g.Sa(d,c||b.g);g.Sa(d,a.Ha.vb);(c=!a.D)&&b3(a);for(var e=a.S&&a.Y&&g.cc(d,a.Y)?a.S:c3(a,d),f="string"===typeof b.text,k=f?b.text.split("\n"):[b.text],l=0;l<k.length;l++){var m=0<l||!b.l,n=k[l];m&&!c?(b3(a),e=c3(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.Sd(n):n),f||"RUBY"!=n.tagName||4!=n.childElementCount||g.Ty||!g.eg(n.children[2],"text-emphasis")||(m=a.u?"padding-right":"padding-top",g.eg(n.children[2],"text-emphasis-position")&&(m=a.u?"padding-left":"padding-bottom"),g.Nd?
g.ag(e,m,"1em"):g.ag(e,m,"0.5em")))}a.Y=d;a.S=e;a.C.push(b)},e3=function(){},g3=function(){this.o=this.i=this.mode=this.l=0;
this.u=new f3(this);this.A=new f3(this);this.g=[];this.clear()},Wpa=function(a,b,c){if(255==a&&255==b||!a&&!b)return{Al:a,
Bl:b,result:0};a=h3[a];b=h3[b];if(a&128){if(!(b&128)&&0!=c.g&&c.i==b)return{Al:a,Bl:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Al:a,Bl:b,result:2};return{Al:a,Bl:b,result:3}},Xpa=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.o&&a.reset(),a.u.g.clear(),a.A.g.clear()):(a.o=0,i3(a.u,b,c,d))},Ypa=function(a,b){a.g.sort(function(e,f){var k=e.time-f.time;
return 0==k?e.order-f.order:k});
for(var c=0;c<a.g.length;c++){var d=a.g[c];a.i=d.time;0==d.type?Xpa(a,d.Du,d.Eu,b):1==d.type&&a.l&496&&i3(a.A,d.Du,d.Eu,b)}a.g.length=0},j3=function(){this.g=0},k3=function(){this.i=this.l=this.g=0},l3=function(){this.timestamp=this.Wd=0},m3=function(a){this.l=[];
for(var b=0;15>=b;b++){this.l[b]=[];for(var c=0;32>=c;c++)this.l[b][c]=new l3}this.g=this.i=this.row=0;this.style=new j3;this.u=a;this.o=0},n3=function(a,b){if(3==a.style.g){for(var c=0,d=0,e=a.u.i+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,q=d?d:1;32>=q;++q){var t=a.l[m][q];
if(0!=t.Wd){0==c&&(c=m,d=q);n=String.fromCharCode(t.Wd);var w=t.timestamp;w<e&&(e=w);t.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==t.Wd||32==q)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.u(c,d,e,l,f)}else for(d=c=0,f=e=a.u.i+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(q=a.l[k][m],t=q.Wd,0!=t&&(0==c&&(c=k,d=m),n=String.fromCharCode(t),w=q.timestamp,w<=e&&(e=w),l+=n,q.reset()),32==m||0==t)l&&b.u(c,d,e,f,l),e=f,l="",d=c=0},cqa=function(a,b){switch(a){case 0:return Zpa[(b&127)-32];
case 1:return $pa[b&15];case 2:return aqa[b&31];case 3:return bqa[b&31]}return 0},o3=function(a){return a.l[a.row][a.i]},p3=function(a,b,c){2<=b&&1<a.i&&(--a.i,o3(a).Wd=0);
var d=o3(a);d.timestamp=a.u.i+0;d.Wd=cqa(b,c);32>a.i&&a.i++},q3=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.l[b+e][f].eg(a.l[c+e][f])},r3=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.l[b+d][e].reset()},s3=function(a){a.row=0<a.g?a.g:1;
a.i=1;r3(a,0,15)},t3=function(a){this.o=a;
this.u=0;this.style=new j3;this.A=new m3(a);this.C=new m3(a);this.D=new m3(a);this.i=this.A;this.l=this.C;this.g=this.i},u3=function(a,b,c){var d=a.i,e=!1;
switch(a.style.get()){case 4:if(0<d.g)break;case 1:case 2:n3(d,c),s3(a.i),s3(a.l),d.row=15,d.g=b,e=!0}a.style.set(3);a.g=d;a.g.style=a.style;a.o.mode=1<<d.o;e?d.i=1:d.g!=b&&(d.g>b?(n3(d,c),r3(d,d.row-d.g,b)):d.row<b&&(b=d.g),d.g=b)},v3=function(a){a.style.set(1);
a.g=a.l;a.g.g=0;a.g.style=a.style;a.o.mode=1<<a.g.o},w3=function(a){a.style.set(4);
a.g=a.D;a.g.style=a.style;a.o.mode=1<<a.g.o},f3=function(a){this.i=a;
this.g=new k3;this.u=0;this.l=new t3(a);this.A=new t3(a);this.o=this.l},i3=function(a,b,c,d){a.g.update();
b=Wpa(b,c,a.g);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Al;c=b.Bl;if(32<=e||!e)a.i.mode&a.i.l&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.o.g,b&96&&p3(a,0,b),c&96&&p3(a,0,c),0!=b&&0!=c&&3==a.style.g&&n3(a,d));else if(e&16)a:if(!a.g.matches(e,c)&&(b=a.g,b.l=e,b.i=c,b.g=2,b=e&8?a.A:a.l,a.o=b,a.i.mode=1<<(a.u<<2)+(b.u<<1)+(4==b.style.g?1:0),(a.i.mode|1<<(a.u<<2)+(b.u<<1)+(4!=b.style.g?1:0))&a.i.l))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&14)>>1):
0;c=b.g;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!=c.row){if(d<c.g&&(d=c.g,d==c.row))break;var f=1+c.row-c.g,k=1+d-c.g;q3(c,k,f,c.g);b=f;e=c.g;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));r3(c,b,e)}}c.row=d;c.i=a+1}else switch(e&7){case 1:switch(c&112){case 32:p3(b.g,0,32);break a;case 48:57==c?(d=b.g,o3(d).Wd=0,32>d.i&&d.i++):p3(b.g,1,c&15)}break;case 2:c&32&&p3(b.g,2,c&31);break;case 3:c&32&&p3(b.g,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:v3(b);break;case 33:d=
b.g;1<d.i&&(--d.i,o3(d).Wd=0);break;case 36:d=b.g;b=o3(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.l[a][c]==b){for(;32>=c;c++)d.l[a][c].reset();break}break;case 37:u3(b,2,d);break;case 38:u3(b,3,d);break;case 39:u3(b,4,d);break;case 40:p3(b.g,0,32);break;case 41:b.style.set(2);b.g=b.i;b.g.g=0;b.g.style=b.style;b.o.mode=1<<b.g.o;break;case 42:d=b.D;d.g=15;d.style.set(4);s3(d);w3(b);break;case 43:w3(b);break;case 44:a=b.i;switch(b.style.get()){case 1:case 2:case 3:n3(a,d)}r3(a,0,15);break;case 45:b:{a=
b.g;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.i=1;break b}case 3:}2>a.g&&(a.g=2,a.row<a.g&&(a.row=a.g));b=a.row-a.g+1;n3(a,d);q3(a,b,b+1,a.g-1);r3(a,a.row,1)}break;case 46:r3(b.l,0,15);break;case 47:n3(b.i,d),b.l.updateTime(b.o.i+0),d=b.l,b.l=b.i,b.i=d,v3(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.g,32<(d.i+=c&3)&&(d.i=32)}}},x3=function(a,b,c,d,e,f,k){var l=f[0],m=k[l.getAttribute("p")];
if(1==m.dd){var n=f[1],q=f[2],t=f[3];l.getAttribute("p");var w=g.eq();l.getAttribute("t");n.getAttribute("t");q.getAttribute("t");t.getAttribute("t");f=w?g.Rd("DIV"):g.Rd("RUBY");l=l.textContent;var z=g.Rd("SPAN");z.innerText=l;f.appendChild(z);n.getAttribute("p");z=w?g.Rd("DIV"):g.Rd("RP");l=n.textContent;z.innerText=l;f.appendChild(z);k=k[q.getAttribute("p")];l=q.textContent;q=w?g.Rd("DIV"):g.Rd("RT");q.innerText=l;f.appendChild(q);l=k.dd;if(10==l||11==l||12==l||13==l||14==l)if(g.ag(q,"text-emphasis",
"filled circle"),g.ag(q,"webkit-text-emphasis","filled circle"),k.dd==k.dd==11||13==k.dd)g.ag(q,"webkit-text-emphasis-position","under left"),g.ag(q,"text-emphasis-position","under left");q=!0;if(4==k.dd||7==k.dd||12==k.dd||14==k.dd)g.ag(f,"ruby-position","over"),g.ag(f,"-webkit-ruby-position","before");else if(5==k.dd||6==k.dd||11==k.dd||13==k.dd)g.ag(f,"ruby-position","under"),g.ag(f,"-webkit-ruby-position","after"),q=!1;t.getAttribute("p");l=t.textContent;t=w?g.Rd("DIV"):g.Rd("RP");t.innerText=
l;f.appendChild(t);w&&(w=q,g.ag(f,{display:"inline-block",position:"relative"}),t=f.firstElementChild.nextElementSibling,g.ag(t,"display","none"),t=t.nextElementSibling,g.ag(t,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",left:"50%",transform:"translateX(-50%)",width:"400%"}),g.ag(f.lastElementChild,"display","none"),w?(g.ag(f,"padding-top","0.6em"),g.ag(t,"top","0")):(g.ag(f,"padding-bottom","0.6em"),g.ag(t,"bottom","0")));return new V2(a,b,e,c,f,d,m)}switch(m.dd){case 9:case 10:m.Ae=
1;break;case 11:m.Ae=2;break;case 12:m.Ae=3;break;case 13:m.Ae=4;break;case 14:m.Ae=5}return new V2(a,b,e,c,l.textContent||"",d,m)},y3=function(){g.F.apply(this,arguments)},z3=function(a){y3.call(this);
this.l={};this.F={};this.H={};this.u="_"+X2++;this.A=a;this.D={};this.i=this.g=null;this.C=!0},A3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return parseFloat(c)},B3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},C3=function(a,b){var c=A3(a,b);
return void 0!=c?c:null},E3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return D3.test(c),c},F3=function(a,b){var c={},d=b.getAttribute("ws");
g.Sa(c,d?a.H[d]:a.A);d=C3(b,"mh");null!=d&&(c.Vq=d);d=C3(b,"ju");null!=d&&(c.textAlign=d);d=C3(b,"pd");null!=d&&(c.Be=d);d=C3(b,"sd");null!=d&&(c.BA=d);d=E3(b,"wfc");null!=d&&(c.windowColor=d);d=A3(b,"wfo");void 0!=d&&(c.windowOpacity=d/255);return c},G3=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Sa(c,a.F[d]);d=C3(b,"ap");null!=d&&(c.Uf=d);d=A3(b,"cc");null!=d&&(c.Ol=d);d=A3(b,"ah");null!=d&&(c.Re=d);d=A3(b,"rc");null!=d&&(c.Bk=d);d=A3(b,"av");null!=d&&(c.Fg=d);return c},H3=function(a,b,c,d){var e={};
g.Sa(e,G3(a,b));g.Sa(e,F3(a,b));d?g.cc(e,a.A)?(d=a.u,e=a.A):d="_"+X2++:d=b.getAttribute("id")||"_"+X2++;a=A3(b,"t")+c;b=A3(b,"d")||0x8000000000000;if(2==e.Be||3==e.Be)c=e.Bk,e.Bk=e.Ol,e.Ol=c;return new W2(a,b,0,d,e)},I3=function(a,b,c,d,e,f,k){$2.call(this,a,b,c,d,e,f,k);
this.type=1},J3=function(a,b,c){this.C=c;
this.version=this.A=this.o=this.g=0;this.i=new DataView(a);this.l=[]},K3=function(a){var b=a.g;
a.g+=1;return a.i.getUint8(b)},L3=function(a){var b=a.g;
a.g+=4;return a.i.getUint32(b)},M3=function(a,b){y3.call(this);
this.i=a;this.track="CC3"==b.l?4:0;this.g=new g3;this.g.l=1<<this.track},O3=function(a){if("string"===typeof a)return!1;
a=new J3(a,8,0);return N3(a)},N3=function(a){if(!(a.g<a.i.byteLength)||1380139777!=L3(a))return!1;
a.version=K3(a);if(1<a.version)return!1;K3(a);K3(a);K3(a);return!0},P3=function(a,b,c,d,e,f,k){$2.call(this,a,b,c,d,e,f,k);
g.K(this.element,"ytp-caption-window-rollup");this.type=2;this.F=[];this.I=this.H=this.ea=0;this.M=NaN;this.xa=0;this.Da=null;this.da=new g.J(this.KK,433,this);g.I(this,this.da);g.ag(this.element,"overflow","hidden")},dqa=function(a,b){return(a.u?b.offsetHeight:b.offsetWidth)+1},eqa=function(a){if(isNaN(a.M)){var b=a.l.Ol;
if(b){var c=g.Rd("SPAN");g.ae(c,"\u2013".repeat(b));g.ag(c,a3(a,a.l.vb));a.A.appendChild(c);a.M=c.offsetWidth;a.A.removeChild(c)}else a.M=0}return a.M},fqa=function(a,b){if(!b)return"";
a.u&&1!=a.o.params.BA&&(b*=-1);return"translate"+(a.u?"X":"Y")+"("+b+"px)"},Q3=function(a){a.F=[].concat(g.ea(document.getElementsByClassName("caption-visual-line")));
for(var b=a.o.params.Bk,c=0,d=0,e=a.F.length-1;c<b&&-1<e;){var f=a.F[e];d+=a.u?f.offsetWidth:f.offsetHeight;c++;e--}a.F.length<b&&(d*=b/a.F.length);a.H=d;a.I=Math.max(eqa(a),a.xa,dqa(a,a.A))},gqa=function(a,b){Q3(a);
var c=a.F.reduce(function(e,f){return(a.u?f.offsetWidth:f.offsetHeight)+e},0);
c=a.H-c;if(c!=a.ea){var d=0<c&&0==a.ea;b||isNaN(c)||d||(g.K(a.element,"ytp-rollup-mode"),g.wn(a.da));g.ag(a.A,"transform",fqa(a,c));a.ea=c}Q3(a)},R3=function(){y3.call(this)},S3=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.Qe=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var q=k.childNodes[n];if(3==q.nodeType){q=new V2(b,c,d,e.id,q.nodeValue,f||0<n,g.Zb(l)?void 0:l);m.push(q);var t=e;g.I(t,q);t.g.push(q)}else t={},g.Sa(t,l),S3(a,b,c,d,e,!0,q,t,m)}},T3=function(a){var b=0;
a=g.p(a.split(":"));for(var c=a.next();!c.done;c=a.next())b=60*b+parseFloat(c.value);return 1E3*b},U3=function(a,b,c,d){d=Object.assign({Vq:0},d);
return new W2(a,b,c,"_"+X2++,d)},V3=function(a){g.F.call(this);
this.i=a;this.g=null},Y3=function(a){g.PK.call(this,a);
this.l=g.W(a);this.O=a.getVideoData();this.na=g.lK(a);this.M=a;var b=null,c=g.lo("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.Vn(c));this.Z=b;this.o={vb:{}};this.u={vb:{}};this.F=[];this.R={};this.S={};this.I=!1;this.da=g.hV(this.O,this.M);this.va=!!this.O.captionTracks.length;this.wa=!!this.O.dj;this.ma="3"==this.l.l;b=a.app.u;c=!(!b||!b.Pk());this.la=!(!b||!b.Ah());this.A=this.ma&&c&&!this.da;this.H=!this.A&&this.ma&&this.la&&this.da;this.i=this.C=this.D=this.P=this.ea=null;this.Y=
new V3(this.l);g.I(this,this.Y);c=b=this.g=null;this.A||(b=new g.tn(this.QA,void 0,this),g.I(this,b),c=new g.J(this.lM,2E3,this),g.I(this,c));this.W=b;this.X=c;this.ba=new g.hs(this);g.I(this,this.ba);this.A||this.ba.K(a,"resize",this.Xs);this.ba.K(a,"onPlaybackAudioChange",this.mI);this.ba.K(a,g.ND("captions"),this.bF,this);this.ba.K(a,"crx_captions",this.cF,this);W3(this,X3(this,"display-settings")||{})},Z3=function(a){if(1==a.l.Zf||1==a.O.Zf||"alwayson"==g.vB(a.O,"yt:cc"))return!0;
if(2==a.l.Zf){var b=X3(a,"module-enabled");if(null!=b)return!!b}if(a.O.captionTracks.length)var c=a.player.getAudioTrack().lp;return"ON"==c||"on"==g.vB(a.O,"yt:cc")},$3=function(a,b){if(a.g&&(void 0===b||!b)||!a.O.captionTracks.length)return!1;
var c=a.player.getAudioTrack();return!!c.Zl||"FORCED_ON"==c.lp},b4=function(a,b){if(a.i){if(a.C&&a.C.g)return a.C.g;
var c=b;c||(c=a.wa?!1:a.va?!1:!0);c=I2(a.i.i,c);for(var d=[a.O.Yf,a.l.Yf,g.vB(a.O,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(H2(c[f])==d[e])return c[f];return a.C&&a.C.Ep?a.C.Ep:(d=c.find(function(k){return k.isDefault}))?d:c[0]||a4(a)}return null},a4=function(a){return a.C&&a.C.Zl},c4=function(a){var b=a4(a);
return!!b&&a.g==b},d4=function(a,b){for(var c=a.M.app.u.ga().textTracks,d=a.g.toString(),e=0;e<c.length;e++){var f=c[e];
f.id==d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"==f.mode&&(f.mode="disabled"))}},f4=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.I=c,a.I&&e4(a,"module-enabled",!!b));a.g=b;$3(a)&&(a.g=a4(a));a.load()},hqa=function(a,b){var c=a.na.getVideoContentRect(!0).height;
if(!c)return null;var d=a.na.getPlayerSize();switch(null!=b.params.Vq?b.params.Vq:1<b.g.length?1:0){case 1:return new I3(b,a.o,a.u,c,d.width,d.height,a.l.experiments);case 2:return new P3(b,a.o,a.u,c,d.width,d.height,a.l.experiments);default:return new $2(b,a.o,a.u,c,d.width,d.height,a.l.experiments)}},W3=function(a,b,c){var d=g4.vb;
a.o={};g.Sa(a.o,g4);a.o.vb={};g.Sa(a.o.vb,d);a.u={vb:{}};var e=b.backgroundOverride?a.u:a.o,f=b.background||d.background;D3.test(f);e.vb.background=f;e=b.colorOverride?a.u:a.o;f=b.color||d.color;D3.test(f);e.vb.color=f;e=b.windowColorOverride?a.u:a.o;f=b.windowColor||g4.windowColor;D3.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.u:a.o;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.vb.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.u:a.o;f=b.fontSizeIncrement;null==f&&(f=d.fontSizeIncrement);
e.vb.fontSizeIncrement=f;f=b.fontStyleOverride?a.u:a.o;e=b.fontStyle;null==e&&(e=d.bold&&d.Qe?3:d.bold?1:d.Qe?2:0);f=f.vb;switch(e){case 1:f.bold=!0;delete f.Qe;break;case 2:delete f.bold;f.Qe=!0;break;case 3:f.bold=!0;f.Qe=!0;break;default:delete f.bold,delete f.Qe}e=b.textOpacityOverride?a.u:a.o;f=b.textOpacity;null==f&&(f=d.textOpacity);e.vb.textOpacity=f;e=b.windowOpacityOverride?a.u:a.o;f=b.windowOpacity;null==f&&(f=g4.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?a.u:a.o;f=b.charEdgeStyle;
null==f&&(f=d.charEdgeStyle);e.vb.charEdgeStyle=f;e=b.fontFamilyOverride?a.u:a.o;f=b.fontFamily;null==f&&(f=d.fontFamily);e.vb.fontFamily=f;a.loaded&&a.Xs();c&&e4(a,"display-settings",b)},i4=function(a,b){if(b&&!a.D){var c=Y2({Be:0,
lang:"en"});a.D=[c,new V2(c.start,c.end-c.start,0,c.id,"Captions look like this")];g.sK(a.player,a.D)}else!b&&a.D&&(h4(a,a.D),a.D=null)},h4=function(a,b){g.uK(a.player,b);
(0,g.y)(b,function(c){g.fb(this.F,c)},a);
a.W.zj()},X3=function(a,b){if(!a.Z)return null;
try{var c=a.Z.get(b)}catch(d){a.Z.remove(b)}return c},e4=function(a,b,c){if(a.Z)try{a.Z.set(b,c)}catch(d){}};
g.eC.prototype.fj=g.ca(13,function(){for(var a=g.Dd(document,"track",void 0,this.g),b=0;b<a.length;b++)g.Wd(a[b])});
g.KW.prototype.fj=g.ca(12,function(){this.g.fj()});
g.eC.prototype.Pk=g.ca(11,function(){return!!this.g.textTracks});
g.KW.prototype.Pk=g.ca(10,function(){return this.g.Pk()});
g.eC.prototype.Xi=g.ca(9,function(a){for(var b=0;b<a.length;b++)this.g.appendChild(a[b])});
g.KW.prototype.Xi=g.ca(8,function(a){this.g.Xi(a)});
g.WB.prototype.Ah=g.ca(7,function(){});
g.eC.prototype.Ah=g.ca(6,function(){return!(!this.g.textTracks||!this.g.textTracks.addEventListener)});
g.KW.prototype.Ah=g.ca(5,function(){return this.g.Ah()});
g.oz.prototype.dr=g.ca(3,function(a){return a?this.toString()==a.toString():!1});
g.ht.prototype.rm=g.ca(2,function(a){return(a=this.kg(a))?a.i:0});
g.iw.prototype.rm=g.ca(1,function(){return 0});
var iqa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,D3=/^#(?:[0-9a-f]{3}){1,2}$/i;g.r(K2,g.F);K2.prototype.Dz=function(){return!1};
K2.prototype.V=function(){this.Gg();g.F.prototype.V.call(this)};
g.r(L2,K2);L2.prototype.Tq=function(a,b,c){b=this.yj(a,b);var d=(0,g.x)(function(e){this.g=null;c(e.responseText,a)},this);
this.Gg();this.g=g.Wp(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
L2.prototype.Uq=function(a){if(this.l)for(var b=g.p(this.l.captionTracks),c=b.next();!c.done;c=b.next())J2(this.i,c.value);a()};
L2.prototype.yj=function(a,b){var c=a.F,d={fmt:b};("srv3"==b||"3"==b)&&this.Va&&g.O(this.Va.experiments,"caption_rendering_features")&&(g.eq()?Object.assign(d,{xorb:2,xobt:1,xovt:1}):Object.assign(d,{xorb:2,xobt:3,xovt:3}));a.g&&(d.tlang=H2(a));return g.Fp(c,d)};
L2.prototype.Gg=function(){this.g&&this.g.abort()};
M2.prototype.contains=function(a){a=g.qb(this.Ua,a);return 0<=a||0>a&&1==(-a-1)%2};
M2.prototype.length=function(){return this.Ua.length/2};
g.r(N2,g.F);g.h=N2.prototype;g.h.V=function(){g.F.prototype.V.call(this);this.i&&this.i.cancel()};
g.h.Ix=function(){O2(this,this.l.getCurrentTime())};
g.h.reset=function(){this.u=new M2;this.i&&(this.i.cancel(),this.i=null)};
g.h.bx=function(){var a;if(a=null!==this.g)a=this.g,a=a.g.Hf(a);!a||this.i||this.g&&30<this.g.startTime-this.l.getCurrentTime()||(a=this.g,a=a.g.mi(a),a.g[0].duration?(this.u.contains(a.g[0].i)||P2(this,a),this.g=g.Xa(a.g)):!g.O(this.R.experiments,"force_caption_seek_for_live_killswitch")&&this.g&&this.g.u&&this.g.u+this.l.Ab()<this.l.getCurrentTime()&&O2(this,this.l.getCurrentTime()));this.D.start()};
g.h.FK=function(a){var b=!(this.A?a.response:a.responseText)||400<=a.status,c=g.pw(a);c?(a=g.yv(this.o,this.H,{}),b=this.o,g.tv(b.i,a,c),b.requestId=a.get("req_id"),P2(this,this.o)):(b||null===this.C||(c=this.o.g[0],this.A?this.C(a.response,1E3*(c.startTime+this.l.Ab())):this.C(a.responseText,1E3*(c.startTime+this.l.Ab()))),this.i=this.o=null)};
g.r(Q2,K2);g.h=Q2.prototype;g.h.Tq=function(a,b,c){this.Gg();b=Spa(this,a.getId());b||(b=a.i,b=this.g.i?S2(this,b,"386"):S2(this,b));if(b){var d=1E3*(b.index.rm(b.index.ue())-b.index.Kc(b.index.ue()));this.l=new N2(new g.Ou,this.C,b,function(e,f){c(e,a,f,d)},this.A||g.Iu(b.info),(0,g.x)(function(){this.l&&this.l.reset();
this.o=!0},this))}};
g.h.Dz=function(){var a=this.o;this.o=!1;return a};
g.h.Uq=function(a){var b;this.A?b=[new g.oz({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.oz({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:b=this.g.i?R2(this,"386"):R2(this);b=g.p(b);for(var c=b.next();!c.done;c=b.next())J2(this.i,c.value);a()};
g.h.Gg=function(){this.l&&(this.l.dispose(),this.l=null)};
g.h.yj=function(){return""};
g.r(T2,K2);T2.prototype.Tq=function(a,b,c){b=this.yj(a,b);var d=(0,g.x)(function(e){this.g=null;c(e.responseText,a)},this);
this.Gg();this.g=g.Wp(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
T2.prototype.Uq=function(a){var b=this.o,c={type:"list",tlangs:1,v:this.l,vssids:1};this.A&&(c.asrs=1);b=g.Fp(b,c);c=(0,g.x)(function(d){this.g=null;if((d=d.responseXML)&&d.firstChild){for(var e=g.p(d.getElementsByTagName("track")),f=e.next();!f.done;f=e.next()){var k=f.value;f=k.getAttribute("lang_code");var l=k.getAttribute("lang_translated"),m=k.getAttribute("name"),n=k.getAttribute("kind"),q=k.getAttribute("id"),t="true"==k.getAttribute("lang_default"),w="true"==k.getAttribute("cantran");k=k.getAttribute("vss_id");
J2(this.i,new g.oz({languageCode:f,languageName:l,name:m,kind:n,id:q,is_servable:!0,is_translateable:w,vss_id:k,is_default:t}))}d=d.getElementsByTagName("target");e=d.length;for(f=0;f<e;f++)l=d[f].getAttribute("lang_code"),m=d[f].getAttribute("lang_translated"),n=d[f].getAttribute("lang_original"),q=d[f].getAttribute("id"),t="true"==d[f].getAttribute("lang_default"),l={languageCode:l,languageName:m,languageOriginal:n,id:q,isDefault:t},this.C[l.languageCode]=l.languageName,this.u.push(l)}a()},this);
this.Gg();this.g=g.Wp(b,{format:"RAW",onSuccess:c,withCredentials:!0})};
T2.prototype.yj=function(a,b){var c=this.o,d={v:this.l,type:"track",lang:a.i,name:a.getName(),kind:a.o,fmt:b};a.g&&(d.tlang=H2(a));return c=g.Fp(c,d)};
T2.prototype.Gg=function(){this.g&&this.g.abort()};
var Upa=/#(.)(.)(.)/,Tpa=/^#(?:[0-9a-f]{3}){1,2}$/i;var Vpa=["left","right","center","justify"];var g4={windowColor:"#080808",windowOpacity:0,textAlign:2,Uf:7,Re:50,Fg:100,vb:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.r(V2,g.KD);V2.prototype.toString=function(){return g.KD.prototype.toString.call(this)};g.r(W2,g.KD);W2.prototype.toString=function(){return g.KD.prototype.toString.call(this)};
var X2=0;g.r($2,g.V);g.h=$2.prototype;g.h.WF=function(a,b){var c=g.rg(this.element,this.element.parentElement);this.na=a-c.x;this.va=b-c.y;g.K(this.element,"ytp-dragging")};
g.h.VF=function(a,b){var c=g.ug(this.element),d=a-this.na-.02*this.Pa,e=b-this.va-.02*this.Na,f=(d+c.width/2)/this.X*3;f=Math.floor(g.nd(f,0,2));var k=(e+c.height/2)/this.wa*3;k=Math.floor(g.nd(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.X;d=100*g.nd(d,0,1);c=(e+k/2*c.height)/this.wa;c=100*g.nd(c,0,1);this.o.params.Uf=l;this.o.params.Fg=c;this.o.params.Re=d;this.l.Uf=l;this.l.Fg=c;this.l.Re=d;this.bA()};
g.h.UF=function(){g.Fn(this.element,"ytp-dragging")};
g.h.bA=function(){this.wh(this.C)};
g.h.wh=function(a){var b=Math.min(this.Rv(),this.X),c=this.Qv(),d="";3==this.o.params.Be&&(d="rotate(180deg)");g.ag(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.Yo(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.l.Re+2;d=this.l.Uf;switch(d){case 0:case 3:case 6:a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.A.offsetWidth;
b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.l.Fg+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.ag(this.element,a)};
g.h.Yo=function(a){var b;for(b=0;b<a.length&&a[b]==this.C[b];b++);if(this.P||this.C.length>b)b=0,this.P=!1,this.C=[],this.D=this.Y=this.S=null,g.Ud(this.A);for(;b<a.length;b++)d3(this,a[b])};
g.h.Rv=function(){return 0};
g.h.Qv=function(){return 0};
g.h.toString=function(){return g.V.prototype.toString.call(this)};e3.prototype.u=function(){};g3.prototype.clear=function(){this.o=this.i=this.mode=0;this.g=[];this.reset()};
g3.prototype.reset=function(){this.mode=0;this.u.reset(0);this.A.reset(1)};
var h3=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];j3.prototype.set=function(a){this.g=a};
j3.prototype.get=function(){return this.g};
k3.prototype.clear=function(){this.g=0};
k3.prototype.update=function(){this.g=2==this.g?1:0};
k3.prototype.matches=function(a,b){return 0!=this.g&&a==this.l&&b==this.i};
l3.prototype.eg=function(a){this.Wd=a.Wd;this.timestamp=a.timestamp};
l3.prototype.reset=function(){this.timestamp=this.Wd=0};
m3.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.l[b][c].timestamp=a};
m3.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.l[b][c];a=0==d.Wd?a+"_":a+String.fromCharCode(d.Wd)}a+="\n"}return a};
m3.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.l[b][c].reset();this.o=a;this.g=0;this.i=this.row=1};
var Zpa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],$pa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],aqa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],bqa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];t3.prototype.reset=function(a,b){this.u=b;this.style.set(2);this.i=this.A;this.l=this.C;this.g=this.i;var c=(a<<2)+(b<<1);this.A.reset(c);this.C.reset(c);this.D.reset((a<<2)+(b<<1)+1)};
f3.prototype.reset=function(a){this.u=a;this.g.clear();this.o=this.l;this.l.reset(a,0);this.A.reset(a,1)};g.r(y3,g.F);y3.prototype.reset=function(){};g.r(z3,y3);z3.prototype.reset=function(){this.D={};this.i=this.g=null;this.C=!0};
z3.prototype.o=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.p(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.p(e),c=e.next();!c.done;c=e.next())if(c=c.value,1==c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var k=this.l,l={},m=c.getAttribute("p");m&&g.Sa(l,this.l[m]);m=B3(c,"b");null!=m&&(l.bold=
m);m=B3(c,"i");null!=m&&(l.Qe=m);m=B3(c,"u");null!=m&&(l.underline=m);m=C3(c,"et");null!=m&&(l.charEdgeStyle=m);m=C3(c,"of");null!=m&&(l.offset=m);m=E3(c,"bc");null!=m&&(l.background=m);m=E3(c,"ec");null!=m&&(l.Ju=m);m=E3(c,"fc");null!=m&&(l.color=m);m=C3(c,"fs");null!=m&&0!=m&&(l.fontFamily=m);m=A3(c,"sz");void 0!=m&&(l.fontSizeIncrement=m/100-1);m=A3(c,"bo");void 0!=m&&(l.backgroundOpacity=m/255);m=A3(c,"fo");void 0!=m&&(l.textOpacity=m/255);m=C3(c,"rb");null!=m&&10!=m&&0!=m&&(l.dd=10<m?m-1:m);
m=C3(c,"hg");null!=m&&(l.WD=m);c=C3(c,"te");null!=c&&(2==c&&(l.bold=!1,c=1),l.Ae=c);k[d]=l;break;case "ws":d=c.getAttribute("id");this.H[d]=F3(this,c);break;case "wp":d=c.getAttribute("id"),this.F[d]=G3(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.p(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "w":this.g=H3(this,d,e,!1);g.I(this,this.g);(d=this.D[this.g.id])&&d.end>this.g.start&&(d.end=this.g.start);this.D[this.g.id]=this.g;c.push(this.g);break;case "p":var n=
e;k=[];l=d.getAttribute("w")||this.u;m=!!B3(d,"a");n=(A3(d,"t")||0)+n;var q=A3(d,"d")||5E3;m||(!this.C&&this.i&&this.i.windowId==l&&this.i.end>n&&(this.i.end=n),this.i&&"\n"==this.i.text&&(this.i.text=""));var t=m?6:5,w=this.l[d.getAttribute("p")],z=[].concat(g.ea(d.childNodes));z.length&&(this.C=null!=d.getAttribute("d"));for(var C=0;C<z.length;C++){var E=z[C],G=void 0;0<C&&(m=!0);var H=void 0;1==E.nodeType&&(H=E);if(H&&"s"==H.tagName){if((E=this.l[H.getAttribute("p")])&&E.dd&&(1==E.dd?(E=z.slice(C,
C+4),4==E.length&&(G=x3(n,q,l,m,t,E,this.l),C+=3)):G=x3(n,q,l,m,t,[H],this.l)),!G){var P=H;G=n;H=q;E=l;var Q=m,ia=t,pa=P.textContent?P.textContent:"",Ua=this.l[P.getAttribute("p")];P=A3(P,"t")||0;G=new V2(G+P,H-P,ia,E,pa,Q,Ua)}}else G=new V2(n,q,t,l,E.textContent||"",m,w);k.push(G);this.i=G}if(0<k.length)for(k[0].windowId==this.u&&(this.g=H3(this,d,e,!0),g.I(this,this.g),c.push(this.g)),d=g.p(k),k=d.next();!k.done;k=d.next())k=k.value,k.windowId=this.g.id,l=this.g,g.I(l,k),l.g.push(k),c.push(k)}e=
c}else e=[];return e};g.r(I3,$2);I3.prototype.Yo=function(a){var b=this.o.g;$2.prototype.Yo.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.g==e)var d=f;else{d={};g.Sa(d,c.g);g.Sa(d,jqa);var e=c.g;var f=d}d3(this,c,d)}};
var jqa={UD:!0};g.r(J3,e3);J3.prototype.u=function(a,b,c,d,e){if(c<d){var f="_"+X2++;c=c/1E3-this.C;d=d/1E3-this.C;a=new W2(c,d-c,5,f,{textAlign:0,Uf:0,Re:2.5*b,Fg:5.33*a});e=new V2(c,d-c,5,f,e);this.l.push(a);this.l.push(e)}};
g.r(M3,y3);M3.prototype.o=function(a){a=new J3(a,a.byteLength,this.i);if(N3(a)){for(;a.g<a.i.byteLength;)for(0==a.version?a.o=L3(a)*(1E3/45):1==a.version&&(a.o=4294967296*L3(a)+L3(a)),a.A=K3(a);0<a.A;a.A--){var b=K3(a),c=K3(a),d=K3(a);b&4&&(b&3)==this.track&&(0==this.track||1==this.track)&&(b=this.g,b.g.push({time:a.o,type:this.track,Du:c,Eu:d,order:b.g.length}))}Ypa(this.g,a);return a.l}return[]};
M3.prototype.reset=function(){this.g.clear()};g.r(P3,$2);g.h=P3.prototype;g.h.bA=function(){g.xn(this.da)};
g.h.KK=function(){g.Fn(this.element,"ytp-rollup-mode");this.wh(this.Da,!0)};
g.h.Qv=function(){return this.u?this.I:this.H};
g.h.Rv=function(){return this.u?this.H:this.I};
g.h.wh=function(a,b){this.Da=a;if(this.o.params.Bk){for(var c=0,d=0;d<this.C.length&&c<a.length;d++)this.C[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.C.concat(a.slice(c)));this.xa=this.I;this.H=this.I=0;$2.prototype.wh.call(this,a);gqa(this,b);$2.prototype.wh.call(this,a)}else $2.prototype.wh.call(this,a)};g.r(R3,y3);
R3.prototype.o=function(a,b){for(var c=[],d=a.split(kqa),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!lqa.test(f)){var l=j4.exec(f);if(l&&4<=l.length){var m=T3(l[1]),n=T3(l[2])-m;m+=k;var q,t=q=void 0,w=void 0,z=void 0,C=l[3];l={textAlign:2};C=g.p(C?C.split(" "):[]);for(var E=C.next();!E.done;E=C.next())if(E=E.value.split(":"),2==E.length){var G=E[1];switch(E[0]){case "line":E=G.split(",");E[0].endsWith("%")&&(z=E[0],l.Fg=Number.parseInt(z,10),2==E.length&&(w=E[1].trim()));break;case "position":E=G.split(",");
t=E[0];l.Re=Number.parseInt(t,10);2==E.length&&(q=E[1].trim());break;case "align":switch(G){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}z||(l.Fg=100,w||(w="end"));if(!t)switch(l.textAlign){case 0:l.Re=0;break;case 1:l.Re=100;break;default:l.Re=50}t=0;switch(w){case "center":t+=3;break;case "end":t+=6;break;default:t+=0}switch(q){case "line-left":t+=0;break;case "center":t+=1;break;case "line-right":t+=2;break;default:switch(l.textAlign){case 0:t+=
0;break;case 2:t+=1;break;case 1:t+=2}}l.Uf=0>t||8<t?7:t;q=l;f=f.substring(j4.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");t=q;q=f;f={};if(0>q.indexOf("<")&&0>q.indexOf("&"))k=U3(m,n,5,t),n=new V2(m,n,5,k.id,q,!1,g.Zb(f)?void 0:f),c.push(k),c.push(n),g.I(k,n),k.g.push(n);else for(w=q.split(mqa),1==w.length?(q=5,t=U3(m,n,q,t)):(z=q=6,t=Object.assign({Ol:32},t),t=new W2(m,n,z,"_"+X2++,t)),c.push(t),z=m,l=0;l<w.length;l++)C=w[l],0==l%2?(E=g.CY("<html>"+C+"</html>"),E.getElementsByTagName("parsererror").length?
(G=E.createElement("span"),G.appendChild(E.createTextNode(C))):G=E.firstChild,S3(this,z,n-(z-m),q,t,0<l,G,f,c)):z=T3(C)+k}j4.lastIndex=0}}return c};
var lqa=/^NOTE/,kqa=/(?:\r\n|\r|\n){2,}/,j4=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),mqa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.r(V3,g.F);V3.prototype.clear=function(){this.g&&this.g.dispose();this.g=null};
V3.prototype.reset=function(){this.g&&this.g.reset()};
V3.prototype.V=function(){this.clear();g.F.prototype.V.call(this)};g.r(Y3,g.PK);g.h=Y3.prototype;g.h.V=function(){if(this.A||this.H){var a=this.M.app.u;a&&a.fj()}else i4(this,!1);g.PK.prototype.V.call(this)};
g.h.Gk=function(){return this.ma?this.A||this.H:$3(this)?!0:Z3(this)};
g.h.load=function(){g.PK.prototype.load.call(this);var a=!g.O(this.l.experiments,"web_player_captions_track_list_changed_killswitch");this.C=this.player.getAudioTrack();if(this.i)this.g&&(this.Y.clear(),this.A?d4(this,!0):3!=this.player.getPresentingPlayerType()&&this.i.Tq(this.g,"srv3",(0,g.x)(this.sL,this)),!a||this.A||this.H||c4(this)||this.player.ka("captionschanged",G2(this.g))),a||(this.g&&!c4(this)?this.player.ka("captionschanged",G2(this.g)):this.player.ka("onCaptionsTrackListChanged"));else{var b;
this.da?b=new Q2(this.O.ha,this.player):this.va?b=new L2(this.l,this.O,this.player.getAudioTrack()):b=new T2(this.O.dj,this.O.videoId,this.O.Yf||this.l.Yf||g.vB(this.O,"yt:cc_default_lang")||this.l.ec,this.O.jp,this.l);this.i=b;g.I(this,this.i);b.Uq((0,g.x)(this.rL,this))}};
g.h.unload=function(){this.A&&this.g?d4(this,!1):(this.X&&g.yn(this.X),g.vK(this.player,"captions"),this.F=[],this.i&&this.i.Gg(),this.Y.clear(),this.D&&g.sK(this.player,this.D),this.Xs());g.PK.prototype.unload.call(this);var a=g.U(this.player.app);a&&g.ZH(a.u);this.player.ka("captionschanged",{})};
g.h.rL=function(){var a;this.I||Z3(this)?a=b4(this,this.I):$3(this)&&(a=a4(this));if(this.A||this.H){for(var b=I2(this.i.i,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.pz(e),srclang:H2(e),id:e.toString()};this.H||(f.src=this.i.yj(e,"vtt"));e==a&&(f["default"]=1);c.push(g.Qd("TRACK",f))}a=this.M.app.u;a.Xi(c);c=a.ga();this.la&&this.ba.K(c.textTracks,"change",this.tL)}else!this.g&&a&&f4(this,a),this.player.ka("onCaptionsTrackListChanged"),this.player.ka("onApiChange")};
g.h.tL=function(){for(var a=this.M.app.u.ga().textTracks,b=null,c=0;c<a.length;c++)if("showing"==a[c].mode)a:{b=a[c].id;var d=I2(this.i.i,!0);for(var e=0;e<d.length;e++)if(d[e].toString()==b){b=d[e];break a}b=null}(this.loaded?this.g:null)!=b&&f4(this,b,!0)};
g.h.VM=function(){!this.g&&this.A||this.unload()};
g.h.sL=function(a,b,c,d){if(a){this.i.Dz()&&(this.F=[],g.vK(this.M,"captions"),this.W.zj(),this.Y.reset());var e=this.Y;c=c||0;d=d||0;if("string"!==typeof a){var f=new DataView(a);if(8<=f.byteLength&&1718909296==f.getUint32(4)&&(f=g.Dt(f,0,1835295092),a=a.slice(f.dataOffset,f.dataOffset+f.size),!O3(a))){a=new Uint8Array(a);f=[];for(var k=0,l=0;k<a.length;){var m=a[k++];if(128>m)f[l++]=String.fromCharCode(m);else if(191<m&&224>m){var n=a[k++];f[l++]=String.fromCharCode((m&31)<<6|n&63)}else if(239<
m&&365>m){n=a[k++];var q=a[k++],t=a[k++];m=((m&7)<<18|(n&63)<<12|(q&63)<<6|t&63)-65536;f[l++]=String.fromCharCode(55296+(m>>10));f[l++]=String.fromCharCode(56320+(m&1023))}else n=a[k++],q=a[k++],f[l++]=String.fromCharCode((m&15)<<12|(n&63)<<6|q&63)}a=f.join("")}}if(a)try{if("string"!==typeof a){var w=a,z=c,C=d;if(!O3(w))throw Error("Invalid binary caption track data");e.g||(e.g=new M3(C,b));var E=e.g.o(w,z)}else{if("WEBVTT"==a.substring(0,6)){b=a;z=c;e.g||(e.g=new R3);var G=e.g.o(b,z);.01>Math.random()&&
g.Uo(Error("Deprecated subtitles format in web player: WebVTT"));w=G}else b:{G=a;z=g.CY(G);if(!z||!z.firstChild){var H=Error("Invalid caption track data");H.params=G;throw H;}if("timedtext"==z.firstChild.tagName){if(3==parseInt(z.firstChild.getAttribute("format"),10)){if(!e.g){G={};if(C=H2(b))G.lang=C,iqa.test(C)&&(G.Be=1);e.g=new z3(G,e.i)}w=e.g.o(z,c);break b}var P=Error("Unsupported subtitles format in web player (Format2)");P.params=G;throw P;}if("transcript"==z.firstChild.tagName){var Q=Error("Unsupported subtitles format in web player (Format1)");
Q.params=G;throw Q;}var ia=Error("Invalid caption track data");ia.params=G;throw ia;}E=w}var pa=E}catch(Ua){g.M(Ua),e.clear(),pa=[]}else pa=[];g.sK(this.player,pa);!this.I||this.H||c4(this)||g.Hy(this.l)||g.Iy(this.l)||(g.yn(this.X),pa=Y2({Uf:0,Re:5,Fg:5,Bk:2,textAlign:0,Be:0,lang:"en"}),this.P=[pa],e=["Click "," for settings"],this.ea||(E=new g.HC(g.XP()),g.I(this,E),this.ea=E.element),E=pa.end-pa.start,(b=g.pz(this.g))&&this.P.push(new V2(pa.start,E,0,pa.id,b)),this.P.push(new V2(pa.start,E,0,pa.id,
e[0]),new V2(pa.start,E,0,pa.id,this.ea,!0),new V2(pa.start,E,0,pa.id,e[1],!0)),g.sK(this.player,this.P),g.wn(this.X));!this.I||this.H||c4(this)||(e4(this,"module-enabled",!0),this.C&&(this.C.g=this.g),(pa=g.U(this.player.app))&&g.ZH(pa.u));this.I=!1}};
g.h.bF=function(a){this.F.push(a);this.W.zj()};
g.h.cF=function(a){g.fb(this.F,a);this.i instanceof Q2&&this.i.A&&g.uK(this.player,[a]);this.W.zj()};
g.h.fM=function(a){if(a instanceof W2){var b=this.R[a.id];b&&b.o!=a&&(b.dispose(),delete this.R[a.id],b=null);b||(b=hqa(this,a))&&(this.R[a.id]=b)}else b=a.windowId,this.S[b]||(this.S[b]=[]),this.S[b].push(a)};
g.h.lM=function(){h4(this,this.P);this.P=null};
g.h.QA=function(){this.W.stop();g.$b(this.S);this.F.sort(g.MD);var a=this.F;if(this.D){var b=(0,g.Xd)(a,function(c){return-1==this.D.indexOf(c)},this);
b.length&&(a=b)}(0,g.y)(a,this.fM,this);g.Mb(this.R,function(c,d){this.S[d]?(c.element.parentNode||g.zK(this.player,c.element,4),c.wh(this.S[d])):(c.dispose(),delete this.R[d])},this)};
g.h.qM=function(){W3(this,{},!0);g.O(this.l.experiments,"web_player_disable_publish_captions_settings_changed_on_reset")||this.player.ka("captionssettingschanged")};
g.h.kD=function(){var a=g4.vb;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.Qe?3:a.bold?1:a.Qe?2:0,textOpacity:a.textOpacity,windowColor:g4.windowColor,windowOpacity:g4.windowOpacity};var b=X3(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.h.WA=function(a,b){var c={};g.Sa(c,X3(this,"display-settings"));g.Sa(c,a);W3(this,c,b);this.player.ka("captionssettingschanged")};
g.h.Xs=function(){!this.A&&this.loaded&&(g.Mb(this.R,function(a,b){a.dispose();delete this.R[b]},this),this.QA())};
g.h.wc=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.nd(b,-2,4);this.WA({fontSizeIncrement:c});return c;case "reload":b&&!this.A&&f4(this,this.g,!0);break;case "stickyLoading":void 0!=b&&this.l.xb&&e4(this,"module-enabled",!!b);break;case "track":if(!this.i)return{};if(b){if(this.A)break;if(!g.Oa(b))break;if(g.Zb(b)){f4(this,null,!0);break}for(var d=I2(this.i.i,!0),e=0;e<d.length;e++){var f=d[e];f.i!=b.languageCode||c&&f.l!=b.languageName||(c=b.translationLanguage?Qpa(f,b.translationLanguage):
f)}!c||c==this.g&&this.loaded||f4(this,c,!0)}else return this.loaded&&this.g&&!c4(this)?G2(this.g):{};return"";case "tracklist":return this.i?(0,g.A)(I2(this.i.i,!(!b||!b.includeAsr)),function(k){return G2(k)}):[];
case "translationLanguages":return this.i?this.i.u.map(function(k){return Object.assign({},k)}):[];
case "sampleSubtitles":this.A||void 0==b||i4(this,!!b)}};
g.h.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.l.xb&&a.push("stickyLoading");return a};
g.h.cq=function(){var a=this.g;return a?{cc:a.A}:{}};
g.h.PM=function(){this.loaded&&this.g&&!c4(this)?(e4(this,"module-enabled",!1),this.unload(),$3(this,!0)&&f4(this,a4(this),!1)):f4(this,c4(this)||!this.g?b4(this,!0):this.g,!0)};
g.h.mI=function(){var a=c4(this);$3(this,a)?f4(this,this.player.getAudioTrack().Zl,!1):this.O.captionTracks.length&&(this.loaded&&this.unload(),this.Gk()&&(a?f4(this,b4(this),!1):this.load()))};g.nV.captions=Y3;})(_yt_player);
