(function(g){var window=this;var l4=function(a,b,c){var d=b.ua();g.L(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.zc(c?c:"mqdefault.jpg");var f=b instanceof g.SA&&b.lengthSeconds?g.UQ(b.lengthSeconds):null,k=!!e;e=k&&"RD"==(new g.OD(e.substr(0,2),e.substr(2))).type;var l=b instanceof g.SA?b.sa:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:b.author,aria_label:b.Yi||g.AN("Watch $TITLE",{TITLE:b.title}),duration:f,url:b.Wh(),is_live:l,is_list:k,
is_mix:e,background:c?"background-image: url("+c+")":""};b instanceof g.QD&&(d.playlist_length=b.getLength());a.update(d)},m4=function(a,b){g.MC.call(this,{B:"div",
U:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.player=a;this.created=!1},n4=function(a){g.V.call(this,{B:"div",
U:["ytp-upnext","ytp-player-content"],L:{"aria-label":"{{aria_label}}"},J:[{B:"div",G:"ytp-cued-thumbnail-overlay-image",L:{style:"{{background}}"}},{B:"span",G:"ytp-upnext-top",J:[{B:"span",G:"ytp-upnext-header",T:"Up Next"},{B:"span",G:"ytp-upnext-title",T:"{{title}}"},{B:"span",G:"ytp-upnext-author",T:"{{author}}"}]},{B:"a",G:"ytp-upnext-autoplay-icon",L:{role:"button",href:"{{url}}","aria-label":"Play next video"},J:[{B:"svg",L:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},J:[{B:"circle",
G:"ytp-svg-autoplay-circle",L:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{B:"circle",G:"ytp-svg-autoplay-ring",L:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{B:"path",G:"ytp-svg-fill",L:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{B:"span",G:"ytp-upnext-bottom",J:[{B:"span",G:"ytp-upnext-cancel"},{B:"span",G:"ytp-upnext-paused",T:"Autoplay is paused"}]}]});
this.A=null;var b=this.i["ytp-upnext-cancel"];this.A=new g.V({B:"button",U:["ytp-upnext-cancel-button","ytp-button"],L:{tabindex:"0","aria-label":"Cancel autoplay"},T:"Cancel"});g.I(this,this.A);this.A.ca("click",this.rI,this);this.A.g(b);this.l=a;this.I=this.i["ytp-svg-autoplay-ring"];this.D=this.C=this.o=this.u=null;this.F=new g.J(this.Nl,5E3,this);g.I(this,this.F);this.H=0;this.K(this.i["ytp-upnext-autoplay-icon"],"click",this.eK);this.Iy();this.K(a,"autonavvisibility",this.Iy);this.K(a,"mdxnowautoplaying",
this.yJ);this.K(a,"mdxautoplaycanceled",this.zJ);this.K(a,"mdxautoplayupnext",this.VA);3==this.l.getPresentingPlayerType()&&(a=(a=g.mK(g.gK(this.l)))?a.iD():null)&&this.VA(a)},o4=function(a,b){if(!a.o){g.ip("a11y-announce","Up Next "+a.u.title);
a.H=(0,g.dr)();a.o=new g.J((0,g.x)(a.Xo,a,b),25);a.Xo(b);var c=b||g.R(g.W(a.l).experiments,"autoplay_time")||1E4;a.l.ka("onAutonavCoundownStarted",c)}g.Fn(a.element,"ytp-upnext-autoplay-paused")},q4=function(a){p4(a);
a.H=(0,g.dr)();a.Xo();g.K(a.element,"ytp-upnext-autoplay-paused")},p4=function(a){a.o&&(a.o.dispose(),a.o=null)},r4=function(a,b){b=void 0===b?!1:b;
if(g.O(g.W(a.l).experiments,"autonav_notifications")&&b&&window.Notification&&document.hasFocus){var c=Notification.permission;"default"==c?Notification.requestPermission():"granted"!=c||document.hasFocus()||(c=a.u.ua(),a.Nl(),a.C=new Notification("Up Next",{body:c.title,icon:c.zc()}),a.D=a.K(a.C,"click",a.WJ),a.F.start())}p4(a);a.l.nextVideo(!1,b)},s4=function(a){m4.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.l=new g.V({B:"div",G:"ytp-subscribe-card",J:[{B:"img",G:"ytp-author-image",L:{src:b.Ud}},{B:"div",G:"ytp-subscribe-card-right",J:[{B:"div",G:"ytp-author-name",T:b.author},{B:"div",G:"html5-subscribe-button-container"}]}]});g.I(this,this.l);this.l.g(this.element);this.o=new g.hW("Subscribe",null,"Unsubscribe",null,!0,!1,b.Qf,b.subscribed,"trailer-endscreen",null,null,a);g.I(this,this.o);this.o.g(this.l.i["html5-subscribe-button-container"]);this.hide()},t4=function(a){var b=
g.W(a),c=g.Lw||g.dg?{style:"will-change: opacity"}:void 0,d=b.i,e=["ytp-videowall-still"];
b.g&&e.push("ytp-videowall-show-text");g.V.call(this,{B:"a",U:e,L:{href:"{{url}}",target:d?b.u:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},J:[{B:"div",G:"ytp-videowall-still-image",L:{style:"{{background}}"}},{B:"span",G:"ytp-videowall-still-info",J:[{B:"span",G:"ytp-videowall-still-info-bg",J:[{B:"span",G:"ytp-videowall-still-info-content",L:c,J:[{B:"span",G:"ytp-videowall-still-info-title",T:"{{title}}"},{B:"span",G:"ytp-videowall-still-info-author",
T:"{{author_and_views}}"},{B:"span",G:"ytp-videowall-still-info-live",T:"Live"},{B:"span",G:"ytp-videowall-still-info-duration",T:"{{duration}}"}]}]}]},{B:"span",U:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],J:[{B:"span",G:"ytp-videowall-still-listlabel-icon"},"Playlist",{B:"span",G:"ytp-videowall-still-listlabel-length",J:[" (",{B:"span",T:"{{playlist_length}}"},")"]}]},{B:"span",U:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],J:[{B:"span",G:"ytp-videowall-still-listlabel-mix-icon"},
"Mix",{B:"span",G:"ytp-videowall-still-listlabel-length",T:" (50+)"}]}]});this.A=d;this.l=a;this.o=null;this.u=new g.hs(this);g.I(this,this.u);this.ca("click",this.D);this.ca("keypress",this.F);this.u.K(a,"videodatachange",this.C);g.W(a).D&&g.pO(a.app.Z,this.element,this);this.C()},u4=function(a){g.CK(a.l,a.element);
var b=a.o.ua().videoId,c=a.o.getPlaylistId();g.pY(a.l.app,b,a.o.Eb,c,void 0,void 0)},v4=function(a){m4.call(this,a,"videowall-endscreen");
this.C=a;this.A=0;this.o=[];this.D=this.O=this.u=null;this.F=this.P=!1;this.M=null;this.ba=new g.hs(this);g.I(this,this.ba);this.H=new g.J(g.Ra(g.K,this.element,"ytp-show-tiles"),0);g.I(this,this.H);var b=new g.V({B:"button",U:["ytp-button","ytp-endscreen-previous"],L:{"aria-label":"Previous"},J:[g.CP()]});g.I(this,b);b.g(this.element);b.ca("click",this.HF,this);this.I=new g.HC({B:"div",G:"ytp-endscreen-content"});g.I(this,this.I);this.I.g(this.element);b=new g.V({B:"button",U:["ytp-button","ytp-endscreen-next"],
L:{"aria-label":"Next"},J:[g.DP()]});g.I(this,b);b.g(this.element);b.ca("click",this.GF,this);this.l=new n4(a);g.I(this,this.l);g.zK(this.player,this.l.element,4);this.hide()},w4=function(a){return g.AK(a.player)&&a.tu()&&!a.D},x4=function(a,b){return(0,g.A)(b.suggestions,function(c){c=g.iS(g.W(a.C),c);
g.I(a,c);return c})},y4=function(a){var b=a.Ne();
b!=a.P&&(a.P=b,a.player.N("autonavvisibility"))},A4=function(a){g.PK.call(this,a);
this.g=null;this.i=new g.hs(this);g.I(this,this.i);this.l=g.W(a);z4(a)?this.g=new v4(this.player):this.l.Pa?this.g=new s4(this.player):this.g=new m4(this.player);g.I(this,this.g);g.zK(this.player,this.g.element,4);this.aA();this.i.K(a,"videodatachange",this.aA,this);this.i.K(a,g.ND("endscreen"),this.VE,this);this.i.K(a,"crx_endscreen",this.WE,this)},z4=function(a){a=g.W(a);
return a.Na&&!a.Pa};
g.r(m4,g.MC);m4.prototype.create=function(){this.created=!0};
m4.prototype.destroy=function(){this.created=!1};
m4.prototype.tu=function(){return!1};
m4.prototype.Ne=function(){return!1};g.r(n4,g.V);g.h=n4.prototype;g.h.Nl=function(){this.C&&(this.F.stop(),this.Qa(this.D),this.D=null,this.C.close(),this.C=null)};
g.h.Iy=function(){g.LC(this,this.l.Ne())};
g.h.WJ=function(){window.focus();this.Nl()};
g.h.hide=function(){g.V.prototype.hide.call(this)};
g.h.Xo=function(a){a=a||g.R(g.W(this.l).experiments,"autoplay_time")||1E4;var b=Math.min((0,g.dr)()-this.H,a);a=Math.min(b/a,1);this.I.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.l.getPresentingPlayerType()?r4(this,!0):this.o&&this.o.start()};
g.h.eK=function(a){!g.$d(this.A.element,g.tr(a))&&g.lS(a,this.l)&&r4(this)};
g.h.rI=function(){g.iK(this.l,!0)};
g.h.yJ=function(a){this.l.getPresentingPlayerType();this.show();o4(this,a)};
g.h.VA=function(a){this.l.getPresentingPlayerType();this.u&&this.u.ua().videoId==a.ua().videoId||(this.u=a,l4(this,a,"hqdefault.jpg"))};
g.h.zJ=function(){this.l.getPresentingPlayerType();p4(this);this.hide()};
g.h.V=function(){p4(this);this.Nl();g.V.prototype.V.call(this)};g.r(s4,m4);g.r(t4,g.V);t4.prototype.D=function(a){g.lS(a,this.l,this.A,this.o.Eb||void 0)&&u4(this)};
t4.prototype.F=function(a){switch(a.keyCode){case 13:case 32:g.yr(a)||(u4(this),g.xr(a))}};
t4.prototype.C=function(){var a=this.l.getVideoData(),b=g.W(this.l);this.A=a.Zb?!1:b.i};g.r(v4,m4);g.h=v4.prototype;g.h.create=function(){m4.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.u=x4(this,a),this.O=a);this.Jf();this.ba.K(this.player,"appresize",this.Jf);this.ba.K(this.player,"onVideoAreaChange",this.Jf);this.ba.K(this.player,"videodatachange",this.IF);this.ba.K(this.player,"autonavchange",this.ir);this.ba.K(this.player,"autonavcancel",this.FF);a=this.O.autonavState;a!=this.M&&this.ir(a);this.ba.K(this.element,"transitionend",this.uL)};
g.h.destroy=function(){g.js(this.ba);g.Di(this.o);this.o=[];this.u=null;m4.prototype.destroy.call(this);g.Fn(this.element,"ytp-show-tiles");this.H.stop();this.M=this.O.autonavState};
g.h.tu=function(){return 1!=this.O.autonavState};
g.h.show=function(){m4.prototype.show.call(this);g.Fn(this.element,"ytp-show-tiles");g.W(this.player).g?g.xn(this.H):this.H.start();(this.F||this.D&&this.D!=this.O.clientPlaybackNonce)&&g.iK(this.player,!1);w4(this)?(y4(this),2==this.O.autonavState?g.O(g.W(this.player).experiments,"fast_autonav_in_background")&&3==this.player.getVisibilityState()?r4(this.l,!0):o4(this.l):3==this.O.autonavState&&q4(this.l)):(g.iK(this.player,!0),y4(this))};
g.h.hide=function(){m4.prototype.hide.call(this);q4(this.l);y4(this)};
g.h.uL=function(a){g.tr(a)==this.element&&this.Jf()};
g.h.Jf=function(){if(this.u&&this.u.length){g.K(this.element,"ytp-endscreen-paginate");var a=g.qK(this.C,!0,this.C.isFullscreen()),b=g.bD(this.C);b&&(b=b.Yb()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.u.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var q=b/2,t=e/2,w=b<=f-2&&n>=t*m,z=e<=k-2&&n>=q*m;if((q+1)/t*d/c>c/(q/(t+1)*d)&&z)n-=q*m,e+=2;else if(w)n-=t*m,b+=2;else if(z)n-=
q*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.nd(a.width/m||1,1,1.21);n*=g.nd(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.I.element;g.tg(a,m,n);g.ag(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});c=this.l;f=this.u[0];c.u=f;l4(c,f,"hqdefault.jpg");g.L(this.element,"ytp-endscreen-takeover",w4(this));y4(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(k=0;k<e;k++)if(q=
c,t=0,d&&f>=b-2&&k>=e-2?t=1:0==k%2&&0==f%2&&(2>k&&2>f?0==k&&0==f&&(t=2):t=2),q=g.pd(q+this.A,l),0!=t){w=this.o[c];w||(w=new t4(this.player),this.o[c]=w,a.appendChild(w.element));z=Math.floor(n*k/e);var C=Math.floor(m*f/b),E=Math.floor(n*(k+t)/e)-z-4,G=Math.floor(m*(f+t)/b)-C-4;g.ig(w.element,C,z);g.tg(w.element,G,E);g.ag(w.element,"transitionDelay",(k+f)/20+"s");g.L(w.element,"ytp-videowall-still-mini",1==t);g.L(w.element,"ytp-videowall-still-large",2<t);t=w;q=this.u[q];t.o!=q&&(t.o=q,l4(t,q,g.Dn(t.element,
"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg"),q=(q=q.Eb)&&q.itct)&&(w=t.l,g.W(w).D&&g.qO(w.app.Z,t.element,q));c++}g.L(this.element,"ytp-endscreen-paginate",c<l);for(b=this.o.length-1;b>=c;b--)e=this.o[b],g.Wd(e.element),g.Ci(e);this.o.length=c}};
g.h.IF=function(){var a=this.player.getVideoData();this.O!=a&&(this.A=0,this.u=x4(this,a),this.O=a,this.Jf())};
g.h.GF=function(){this.A+=this.o.length;this.Jf()};
g.h.HF=function(){this.A-=this.o.length;this.Jf()};
g.h.mE=function(){return!!this.l.o};
g.h.ir=function(a){1==a?(this.F=!1,this.D=this.O.clientPlaybackNonce,p4(this.l),this.Fa()&&this.Jf()):(this.F=!0,this.Fa()&&w4(this)&&(2==a?o4(this.l):3==a&&q4(this.l)))};
g.h.FF=function(a){if(a){for(a=0;a<this.o.length;a++)g.DK(this.C,this.o[a].element,!0);this.ir(1)}else this.D=null,this.F=!1;this.Jf()};
g.h.Ne=function(){return this.Fa()&&w4(this)};g.r(A4,g.PK);g.h=A4.prototype;g.h.Gk=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!z4(this.player)||b;a=a.Pc||g.Cy(a.La);var c=g.PX(this.player.app);return b&&!a&&!c};
g.h.Ne=function(){return this.g.Ne()};
g.h.fE=function(){return this.Ne()?this.g.mE():!1};
g.h.V=function(){g.vK(this.player,"endscreen");g.PK.prototype.V.call(this)};
g.h.load=function(){g.PK.prototype.load.call(this);this.g.show()};
g.h.unload=function(){g.PK.prototype.unload.call(this);this.g.hide();this.g.destroy()};
g.h.VE=function(a){this.Gk()&&(this.g.created||this.g.create(),"load"==a.getId()&&this.load())};
g.h.WE=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.aA=function(){g.vK(this.player,"endscreen");var a=this.player.getVideoData();a=new g.KD(Math.max(1E3*(a.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});g.I(this,a);var b=new g.KD(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.I(this,b);g.sK(this.player,[a,b])};g.nV.endscreen=A4;})(_yt_player);
