(function(g){var window=this;var D5=function(a){g.MC.call(this,{B:"div",G:"ytp-miniplayer-ui"});this.player=a;this.H=!1;this.F=this.u=this.l=void 0;this.K(a,"minimized",this.QF);this.K(a,"onStateChange",this.HM)},E5=function(a){g.PK.call(this,a);
this.g=new D5(this.player);this.g.hide();g.zK(this.player,this.g.element,4);a.app.F.g&&(this.load(),g.L(a.getRootNode(),"ytp-player-minimized",!0))};
g.r(D5,g.MC);g.h=D5.prototype;
g.h.show=function(){this.l=new g.tn(this.PF,null,this);this.l.start();if(!this.H){this.C=new g.pW(this.player,this);g.I(this,this.C);g.zK(this.player,this.C.element,4);this.C.A=.6;this.P=new g.sV(this.player);g.I(this,this.P);this.A=new g.V({B:"div",G:"ytp-miniplayer-scrim"});g.I(this,this.A);this.A.g(this.element);this.K(this.A.element,"click",this.jz);var a=new g.V({B:"button",U:["ytp-miniplayer-close-button","ytp-button"],L:{"aria-label":"Close"},J:[g.HP()]});g.I(this,a);a.g(this.A.element);this.K(a.element,
"click",this.Gx);this.o=new g.V({B:"div",G:"ytp-miniplayer-controls"});g.I(this,this.o);this.o.g(this.A.element);this.K(this.o.element,"click",this.jz);var b=new g.V({B:"div",G:"ytp-miniplayer-button-container"});g.I(this,b);b.g(this.o.element);a=new g.V({B:"div",G:"ytp-miniplayer-play-button-container"});g.I(this,a);a.g(this.o.element);var c=new g.V({B:"div",G:"ytp-miniplayer-button-container"});g.I(this,c);c.g(this.o.element);this.M=new g.rT(this.player,this,!1);g.I(this,this.M);this.M.g(b.element);
b=new g.oT(this.player,this);g.I(this,b);b.g(a.element);this.I=new g.rT(this.player,this,!0);g.I(this,this.I);this.I.g(c.element);this.F=new g.LU(this.player,this);g.I(this,this.F);this.F.g(this.A.element);this.u=new g.xT(this.player,this);g.I(this,this.u);g.zK(this.player,this.u.element,4);this.D=new g.V({B:"div",G:"ytp-miniplayer-buttons"});g.I(this,this.D);g.zK(this.player,this.D.element,4);a=new g.V({B:"button",U:["ytp-miniplayer-close-button","ytp-button"],L:{"aria-label":"Close"},J:[g.HP()]});
g.I(this,a);a.g(this.D.element);this.K(a.element,"click",this.Gx);a=new g.V({B:"button",U:["ytp-miniplayer-replay-button","ytp-button"],L:{"aria-label":"Close"},J:[g.VP()]});g.I(this,a);a.g(this.D.element);this.K(a.element,"click",this.DK);this.K(this.player,"presentingplayerstatechange",this.RF);this.K(this.player,"appresize",this.Ra);this.K(this.player,"fullscreentoggled",this.Ra);this.Ra();this.H=!0}0!=this.player.getPlayerState()&&g.MC.prototype.show.call(this);this.u.show();this.player.unloadModule("annotations_module")};
g.h.hide=function(){this.l&&(this.l.dispose(),this.l=void 0);g.MC.prototype.hide.call(this);this.player.app.F.g||(this.H&&this.u.hide(),this.player.loadModule("annotations_module"))};
g.h.V=function(){this.l&&(this.l.dispose(),this.l=void 0);g.MC.prototype.V.call(this)};
g.h.Gx=function(){this.player.stopVideo();this.player.ka("onCloseMiniplayer")};
g.h.DK=function(){this.player.playVideo()};
g.h.jz=function(a){if(a.target==this.A.element||a.target==this.o.element)g.O(g.W(this.player).experiments,"kevlar_miniplayer_scrim_pause")?2==this.player.getPlayerState()?this.player.playVideo():this.player.pauseVideo():this.player.ka("onExpandMiniplayer")};
g.h.QF=function(){g.L(this.player.getRootNode(),"ytp-player-minimized",this.player.app.F.g)};
g.h.PF=function(){this.u.Nc();this.F.Nc();this.l&&this.l.start()};
g.h.RF=function(a){g.T(a.state,32)&&this.C.hide()};
g.h.Ra=function(){var a=this.u,b=g.lK(this.player).getPlayerSize().width;a.Ca=0;a.A=b;a.D=!1;g.zT(a)};
g.h.HM=function(a){this.player.app.F.g&&(0==a?this.hide():this.show())};
g.h.Xa=function(){return this.C};
g.h.Yb=function(){return!1};
g.h.rg=function(){return!1};
g.h.hi=function(){return!1};
g.h.Gs=function(){};
g.h.Sg=function(){};
g.h.lj=function(){};
g.h.pn=function(){return null};
g.h.kr=function(){return new g.Xf(0,0,0,0)};
g.h.handleGlobalKeyDown=function(){return!1};
g.h.handleGlobalKeyUp=function(){return!1};
g.h.vk=function(a,b,c,d,e){var f=0,k=d=0,l=g.ug(a);if(b){c=g.Dn(b,"ytp-prev-button")||g.Dn(b,"ytp-next-button");var m=g.Dn(b,"ytp-play-button");c?f=k=12:m&&(b=g.rg(b,this.element),k=b.x,f=b.y-12)}else k=c-l.width/2,d=25+(e||0);b=g.lK(this.player).getPlayerSize().width;e=f+(e||0);k=g.nd(k,0,b-l.width);e?(a.style.top=e+"px",a.style.bottom=""):(a.style.top="",a.style.bottom=d+"px");a.style.left=k+"px"};
g.h.showControls=function(){};
g.h.lr=function(){};
g.h.Qh=function(){};g.r(E5,g.PK);E5.prototype.init=function(){};
E5.prototype.load=function(){this.player.hideControls();this.g.show()};
E5.prototype.unload=function(){this.player.showControls();this.g.hide()};g.nV.miniplayer=E5;})(_yt_player);
